<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <WebView2EnableCsWinRTProjection>False</WebView2EnableCsWinRTProjection>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0-windows</TargetFrameworks>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Description>ZusiStart</Description>
    <Copyright>Harold Linke</Copyright>
    <Authors>Harold Linke</Authors>
    <Version>8.6.14</Version>
    <Title>ZusiStart</Title>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Platforms>AnyCPU;x64</Platforms>
    <StartupObject>ZusiStart.Startup</StartupObject>
    <ApplicationIcon>Resources\zusistart.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <!--<PackageReference Include="CefSharp.Common.NETCore" Version="131.2.70" />
    <PackageReference Include="CefSharp.Wpf.NETCore" Version="131.2.70" />
    <PackageReference Include="chromiumembeddedframework.runtime" Version="131.2.7" />-->
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="GMap.NET.WinPresentation" Version="2.1.7" />
    <PackageReference Include="IpcCommLib" Version="8.0.1" />
    <PackageReference Include="Makaretu.Dns.Multicast" Version="0.27.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.3.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3650.58" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.1" />
    <PackageReference Include="ZusiDisplayLib" Version="8.0.2" />
    <PackageReference Include="ZusiFahrpultLib" Version="8.0.1" />
    <PackageReference Include="ZusiKlassenLib" Version="8.0.16" />
    <PackageReference Include="ZusiMeterGaugesLib" Version="8.0.2" />
    <PackageReference Include="ZusiPicLib" Version="8.0.1" />
    <PackageReference Include="Zusisuplib" Version="8.0.1" />
  </ItemGroup>
  <ItemGroup>
      
    <None Include="develop.pfx" />
    <None Include="LICENSE" />
    <None Include="log4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </None>
    <None Include="packages.config" />
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <AppDesigner Include="Properties\" />
    <COMReference Include="IWshRuntimeLibrary">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>f935dc20-1cf0-11d0-adb9-00c04fd58a0b</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
    <Content Include="Resources\zusistart.ico" />
    <None Include="README.md" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Default.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Err500.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\classes.family">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Resources\default0.PNG">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\default1.PNG">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\default2.PNG">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\default3.PNG">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Update\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="zusistart.ico" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="About\LGPLv3_Logo.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\DummyPage.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\bkgnd_2.jpg" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\bkgnd_3.jpg" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\default4.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ZusiBfpl">
      <HintPath>dll\ZusiBfpl.dll</HintPath>
    </Reference>
    <Reference Include="ZusiBuchfahrplan2">
      <HintPath>dll\ZusiBuchfahrplan2.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\bkgnd_4.jpg" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\bkgnd_1.jpg" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Fahrschule\Timetables\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fahrschule\webpage\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Update="GaugePool.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="help\ZusiStart_Docu_Deutsch.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="help\ZusiStart_Docu_English.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="help\ZusiStart_Docu_Français.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="history_of_change.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ReplacementLoco.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ReplacementLoco.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ReplacementTrain.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ReplacementTrain.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\NotFound.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ZSK_locationGroupId.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\zusistart.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="libls3render.def">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="libls3render.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NativeStandards.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\GaugePool.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\icons\LE02b.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\icons\Level0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\icons\Level1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\icons\Level2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\icons\Level3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\icons\LevelSTM.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\icons\Levelundefined.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\images\bkgnd.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\images\graphic.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\images\listviewitem.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\images\textbased.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\images\window_bkgnd.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\images\window_bkgnd_blue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\Resources\zusimeter.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\ZusiMeterLayouts\Zusimeter_Standard_Layout.zmlf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\ZusiMeterLayouts\Example01.zmlf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\ZusiMeterLayouts\Example02.zmlf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZusiMeter\ZusiMeterLayouts\Example03.zmlf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Miscellaneous\HttpMiniServer.txt" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Assets\Language_table.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <!--
  <ItemGroup>
    <PackageReference Update="chromiumembeddedframework.runtime.win-x64" Version="131.2.7" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="chromiumembeddedframework.runtime.win-arm64" Version="131.2.7" />
  </ItemGroup>
  -->

</Project>
