<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <LangVersion>9.0</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <AssemblyTitle>ZusiMeter</AssemblyTitle>
    <Copyright>Copyright © 2017-2024 Holger Maaß, Harold Linke</Copyright>
    <Product>ZusiMeter</Product>
    <AssemblyVersion></AssemblyVersion>
    <ApplicationIcon>Resources\zusimeter.ico</ApplicationIcon>
    <StartupObject>ZusiMeter.Startup</StartupObject>
   </PropertyGroup>
  <ItemGroup>
    <Compile Remove="AsmInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\zusimeter.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
   <ItemGroup>
    <PackageReference Include="Sovoma" Version="8.0.1" />
    <PackageReference Include="Sovoma.WPF" Version="8.0.1" />
    <PackageReference Include="System.IO" Version="4.3.0" />
    <PackageReference Include="ZusiFahrpultLib" Version="8.0.1" />
    <PackageReference Include="ZusiMeterGaugesLib" Version="8.0.2" />
    <PackageReference Include="Zusisuplib" Version="8.0.1" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2792.45" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ZusiMeter">
      <HintPath>ZusiMeter.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="images\bkgnd.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="images\graphic.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="images\listviewitem.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="images\textbased.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="images\window_bkgnd.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="images\window_bkgnd_blue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="themes\images\bkgnd.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\zusimeter.ico">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="help\ZusiMeter_Docu_Deutsch.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="zusimeter.xsd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="GaugePool_bak2.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="ZusiMeterExampleLayouts\Example01.zmlf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="ZusiMeterExampleLayouts\Example02.zmlf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="lib\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="themes\images\graphic.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="themes\images\listviewitem.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="themes\images\textbased.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="themes\images\window_bkgnd.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="themes\images\window_bkgnd_blue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>