<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>True</UseWindowsForms>
    <UseWPF>True</UseWPF>
    <Version>0.1.16</Version>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ZusiBfpl">
      <HintPath>dll\ZusiBfpl.dll</HintPath>
    </Reference>
    <Reference Include="ZusiBuchfahrplan2">
      <HintPath>dll\ZusiBuchfahrplan2.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="dll\ZusiBfpl.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="dll\ZusiBuchfahrplan2.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
